'use client';
import {useState,useEffect,useRef} from 'react';
import {Trophy,ArrowUpRight,Timer,RotateCcw,Eraser,ArrowRight,Grid2X2,Sparkles,Check} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
type Score={id:string,name:string,elapsed:number};
const time=(ms:number)=>`${String(Math.floor(ms/60000)).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`;
const demo=[1,0,0,0,0,2,2,0,0,0,0,3,0,1,0,0,4,0,0,2,0,0,1,0,4,0,0,0,0,1,5,0,0,0,0,4];
export default function Game(){
 const [mode,setMode]=useState('mini'),[listMode,setListMode]=useState('mini'),[board,setBoard]=useState<number[]>(demo),[givens,setGivens]=useState<number[]>(demo),[selected,setSelected]=useState(-1),[status,setStatus]=useState('ready'),[id,setId]=useState(''),[elapsed,setElapsed]=useState(0),[scores,setScores]=useState<Score[]>([]),[scoreState,setScoreState]=useState('loading'),[name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false),[history,setHistory]=useState<number[][]>([]),[pulse,setPulse]=useState(-1);
 const startAt=useRef(0),n=mode==='mini'?6:9,bh=mode==='mini'?2:3;
 async function api(data:object){const r=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await r.json() as {error?:string,id:string,puzzle:number[],elapsed:number};if(!r.ok)throw Error(result.error||'Något gick fel.');return result;}
 async function loadScores(m:string){setScoreState('loading');try{const r=await fetch('/api/game?mode='+m);if(!r.ok)throw Error();setScores(await r.json());setScoreState('ok');}catch{setScoreState('error');}}
 useEffect(()=>{loadScores(listMode)},[listMode]);
 useEffect(()=>{if(status!=='playing')return;const t=setInterval(()=>setElapsed(performance.now()-startAt.current),100);return()=>clearInterval(t)},[status]);
 async function start(m=mode){setBusy(true);setError('');try{const r=await api({action:'start',mode:m});setMode(m);setListMode(m);setId(r.id);setBoard(r.puzzle);setGivens(r.puzzle);setHistory([]);setSelected(r.puzzle.indexOf(0));setElapsed(0);startAt.current=performance.now();setStatus('playing');setSaved(false);setName('');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function changeMode(m:string){if(status==='playing'&&!window.confirm('Avsluta rundan och byta svårighetsgrad?'))return;setMode(m);setListMode(m);setStatus('ready');setElapsed(0);setBoard(m==='mini'?demo:Array(81).fill(0));setGivens(m==='mini'?demo:Array(81).fill(0));setSelected(-1);setError('');}
 const conflict=(i:number,b=board)=>b[i]!==0&&b.some((v,j)=>j!==i&&v===b[i]&&(Math.floor(j/n)===Math.floor(i/n)||j%n===i%n||(Math.floor(Math.floor(j/n)/bh)===Math.floor(Math.floor(i/n)/bh)&&Math.floor((j%n)/3)===Math.floor((i%n)/3))));
 async function finish(b:number[]){setBusy(true);try{const r=await api({action:'finish',id,board:b});setElapsed(r.elapsed);setStatus('won');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function enter(v:number){if(status!=='playing'||selected<0||givens[selected]||busy)return;const next=[...board];next[selected]=v;setHistory([...history,board]);setBoard(next);setPulse(selected);setError('');if(next.every(Boolean)&&!next.some((_,i)=>conflict(i,next)))finish(next);}
 function undo(){if(status!=='playing'||!history.length||busy)return;setBoard(history[history.length-1]);setHistory(history.slice(0,-1));}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).tagName==='INPUT'||status!=='playing')return;if(/^[1-9]$/.test(e.key)&&+e.key<=n){e.preventDefault();enter(+e.key)}else if(['Backspace','Delete','0'].includes(e.key)){e.preventDefault();enter(0)}else if(e.key.startsWith('Arrow')){e.preventDefault();setSelected(s=>Math.max(0,Math.min(n*n-1,(s<0?0:s)+({ArrowLeft:-1,ArrowRight:1,ArrowUp:-n,ArrowDown:n}[e.key]||0))))}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)});
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api({action:'score',id,name});setSaved(true);setListMode(mode);await loadScores(mode)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const filled=board.filter(Boolean).length,progress=Math.round(filled/(n*n)*100);
 return <div className="shell"><header><a className="brand" href="/" aria-label="Sudoku startsida"><span className="brandmark"><Grid2X2 size={23}/></span>sudoku<span className="brand-dot">.</span></a><span className="header-note">Lite fokus. Ett nytt rekord.</span><span className="edition">THE NUMBER CLUB <span>01</span></span></header>
 <main><section className="game-area"><div className="intro"><div><div className="eyebrow">DIN DAGLIGA HJÄRNGYMNASTIK</div><h1>Hitta ditt flow<span>.</span></h1><p>En ruta i taget. Hur snabbt löser du det?</p></div><div className="intro-symbol">#</div></div>
 <div className="mode-row"><Tabs value={mode} onValueChange={changeMode}><TabsList className="mode-tabs"><TabsTrigger value="mini" disabled={busy}>Mini <span>6 × 6</span></TabsTrigger><TabsTrigger value="hard" disabled={busy}>Utmanaren <span>9 × 9</span></TabsTrigger></TabsList></Tabs><span className="level-label">{mode==='mini'?'LITEN MEN KLURIG':'MER ATT BITA I'}</span></div>
 <div className="play-card"><div className="board-top"><div><span className={'status-light '+(status==='playing'?'live':'')}/>{status==='playing'?'Rundan pågår':status==='won'?'Snyggt löst!':'Redo när du är'}</div><div className="timer"><Timer size={17}/>{time(elapsed)}<small>.{Math.floor(elapsed%1000/100)}</small></div></div>
 <div className={'board-wrap '+(status==='won'?'celebrate':'')}><div className={'board '+(n===9?'large':'')} style={{gridTemplateColumns:`repeat(${n},1fr)`,gridTemplateRows:`repeat(${n},1fr)`}} role="group" aria-label={`${n} gånger ${n} sudoku`}>
 {board.map((v,i)=>{const related=selected>=0&&(Math.floor(i/n)===Math.floor(selected/n)||i%n===selected%n);return <button key={`${mode}-${i}`} disabled={status!=='playing'||busy} onClick={()=>setSelected(i)} aria-label={`Rad ${Math.floor(i/n)+1}, kolumn ${i%n+1}: ${v||'tom'}${givens[i]?', fast siffra':''}`} aria-pressed={i===selected} className={['cell',givens[i]?'given':'entered',related?'related':'',i===selected?'selected':'',v&&v===board[selected]?'same':'',conflict(i)?'conflict':'',i===pulse?'pop':''].join(' ')} style={{borderRightWidth:(i%n+1)%3===0&&i%n<n-1?2:undefined,borderBottomWidth:(Math.floor(i/n)+1)%bh===0&&Math.floor(i/n)<n-1?2:undefined,animationDelay:`${i*5}ms`}}>{v||''}</button>})}</div>
 {status==='ready'&&<div className="start-cover"><span className="start-icon"><Grid2X2 size={30}/></span><h2>{mode==='mini'?'En liten utmaning.':'Redo för nästa nivå?'}</h2><p>{mode==='mini'?'6 × 6 rutor. Siffrorna 1–6.':'9 × 9 rutor. Siffrorna 1–9.'}</p><button className="primary" onClick={()=>start()} disabled={busy}>{busy?'Förbereder…':'Starta rundan'}<ArrowRight size={18}/></button><span>Klockan startar när brädet är redo.</span></div>}
 {status==='won'&&<div className="win-cover"><div className="confetti">{Array.from({length:18},(_,i)=><i key={i} style={{left:`${i*5.7}%`,animationDelay:`${i*.07}s`}}/>)}</div><Trophy size={40}/><div className="eyebrow">DU LÖSTE DET!</div><h2>{time(elapsed)}<small>.{Math.floor(elapsed%1000/100)}</small></h2>{saved?<p className="saved"><Check size={18}/> Din tid finns på topplistan.</p>:<form onSubmit={save}><label htmlFor="player">Sätt ditt namn på topplistan</label><input id="player" autoFocus maxLength={24} required value={name} onChange={e=>setName(e.target.value)} placeholder="Ditt namn"/><button className="primary" disabled={busy||!name.trim()}>{busy?'Sparar…':'Spara min tid'}<ArrowUpRight size={18}/></button></form>}<button className="text-button" disabled={busy} onClick={()=>start()}>Spela igen <ArrowRight size={16}/></button></div>}
 </div><div className="board-bottom"><span>{status==='ready'?'Ditt nästa rekord börjar här':`${filled} av ${n*n} rutor fyllda`}</span><div className="progress-track"><i style={{width:status==='ready'?'0%':`${progress}%`}}/></div></div></div>
 <div className="controls"><div className="number-pad">{Array.from({length:n},(_,i)=><button key={i} disabled={status!=='playing'||busy} onClick={()=>enter(i+1)}>{i+1}</button>)}</div><div className="tools"><button onClick={undo} disabled={!history.length||status!=='playing'||busy} title="Ångra"><RotateCcw size={19}/><span>Ångra</span></button><button onClick={()=>enter(0)} disabled={status!=='playing'||busy} title="Radera"><Eraser size={19}/><span>Radera</span></button></div></div>
 {error&&<div className="error" role="alert">{error}{status==='playing'&&board.every(Boolean)&&<button onClick={()=>finish(board)} disabled={busy}>Kontrollera igen</button>}</div>}
 <div className="under-board"><span><span className="keycap">1–{n}</span> Använd tangentbordet eller sifferknapparna</span><button disabled={busy} onClick={()=>{if(status!=='playing'||window.confirm('Avsluta rundan och starta ett nytt spel?'))start()}}>Nytt spel <RotateCcw size={14}/></button></div></section>
 <aside><div className="ranking"><div className="rank-heading"><div><div className="eyebrow">SNABBAST TILL SISTA RUTAN</div><h2>Topplistan<span>.</span></h2></div><span className="trophy-icon"><Trophy size={24}/></span></div><Tabs value={listMode} onValueChange={setListMode}><TabsList className="rank-tabs"><TabsTrigger value="mini">Mini 6 × 6</TabsTrigger><TabsTrigger value="hard">Utmanaren 9 × 9</TabsTrigger></TabsList></Tabs><div className="table-labels"><span>PLACERING / SPELARE</span><span>TID</span></div><div className="scores" aria-live="polite">{scoreState==='loading'?<div className="empty">Hämtar tider…</div>:scoreState==='error'?<div className="empty">Topplistan kunde inte hämtas.<button className="text-button" onClick={()=>loadScores(listMode)}>Försök igen</button></div>:scores.length?scores.map((s,i)=><div className={'score '+(i===0?'first':'')} key={s.id}><span className="place">{i===0?<Trophy size={18}/>:String(i+1).padStart(2,'0')}</span><span className="player">{s.name}{i===0&&<small>SNABBAST JUST NU</small>}</span><strong>{time(s.elapsed)}<small>.{Math.floor(s.elapsed%1000/100)}</small></strong></div>):<div className="empty"><Trophy size={34}/><h3>Först hit, först på listan.</h3><p>Lös en runda och sätt tiden<br/>som alla andra ska slå.</p></div>}</div><div className="ranking-footer"><Sparkles size={15}/> Topp 10 · snabbaste rundorna</div></div>
 <div className="rules"><span className="eyebrow">SÅ SPELAR DU</span><h3>Alla siffror. Bara en gång.</h3><p>Fyll varje rad, kolumn och {mode==='mini'?'2 × 3':'3 × 3'}-block med siffrorna 1–{n}. Ingen siffra får upprepas.</p><div className="rule-bottom"><span className="rule-symbol">↳</span><span>Välj en ruta.<br/>Låt logiken göra resten.</span></div></div></aside></main><footer><span>SUDOKU / THE NUMBER CLUB</span><span>Fokus slår gissningar.</span></footer></div>
}
